# encoding: utf-8
from gnr.core.gnrbag import Bag,BagResolver
class Table(object):
    def config_db(self, pkg):
        tbl =  pkg.table('jos_menu',  pkey='id',name_long='jos_menu')
        tbl.column('id', dtype ='I', name_long ='!!Id', notnull ='y')  
        tbl.column('menutype', dtype ='A', name_long ='!!Menutype', size ='0:75')  
        tbl.column('name', dtype ='A', name_long ='!!Name', size ='0:255')  
        tbl.column('alias', dtype ='A', notnull ='y', size ='0:255', name_long ='!!Alias')  
        tbl.column('link', dtype ='T', name_long ='!!Link')  
        tbl.column('type', dtype ='A', notnull ='y', size ='0:50', name_long ='!!Type')  
        tbl.column('published', dtype ='I', name_long ='!!Published', notnull ='y')  
        tbl.column('parent', dtype ='I', name_long ='!!Parent', notnull ='y')  
        tbl.column('componentid', dtype ='I', name_long ='!!Componentid', notnull ='y')  
        tbl.column('sublevel', dtype ='I', name_long ='!!Sublevel')  
        tbl.column('ordering', dtype ='I', name_long ='!!Ordering')  
        tbl.column('checked_out', dtype ='I', name_long ='!!Checked_Out', notnull ='y')  
        tbl.column('checked_out_time', dtype ='DH', name_long ='!!Checked_Out_Time', notnull ='y')  
        tbl.column('pollid', dtype ='I', name_long ='!!Pollid', notnull ='y')  
        tbl.column('browserNav', dtype ='I', name_long ='!!Browsernav')  
        tbl.column('access', dtype ='I', name_long ='!!Access', notnull ='y')  
        tbl.column('utaccess', dtype ='I', name_long ='!!Utaccess', notnull ='y')  
        tbl.column('params', dtype ='T', name_long ='!!Params', notnull ='y')  
        tbl.column('lft', dtype ='I', name_long ='!!Lft', notnull ='y')  
        tbl.column('rgt', dtype ='I', name_long ='!!Rgt', notnull ='y')  
        tbl.column('home', dtype ='I', name_long ='!!Home', notnull ='y')  
