# encoding: utf-8
from gnr.core.gnrbag import Bag,BagResolver
class Table(object):
    def config_db(self, pkg):
        tbl =  pkg.table('jos_banner',  pkey='bid',name_long='jos_banner')
        tbl.column('bid', dtype ='I', name_long ='!!Bid', notnull ='y')  
        tbl.column('cid', dtype ='I', name_long ='!!Cid', notnull ='y')  
        tbl.column('type', dtype ='A', notnull ='y', size ='0:30', name_long ='!!Type')  
        tbl.column('name', dtype ='A', notnull ='y', size ='0:255', name_long ='!!Name')  
        tbl.column('alias', dtype ='A', notnull ='y', size ='0:255', name_long ='!!Alias')  
        tbl.column('imptotal', dtype ='I', name_long ='!!Imptotal', notnull ='y')  
        tbl.column('impmade', dtype ='I', name_long ='!!Impmade', notnull ='y')  
        tbl.column('clicks', dtype ='I', name_long ='!!Clicks', notnull ='y')  
        tbl.column('imageurl', dtype ='A', notnull ='y', size ='0:100', name_long ='!!Imageurl')  
        tbl.column('clickurl', dtype ='A', notnull ='y', size ='0:200', name_long ='!!Clickurl')  
        tbl.column('date', dtype ='DH', name_long ='!!Date')  
        tbl.column('showBanner', dtype ='I', name_long ='!!Showbanner', notnull ='y')  
        tbl.column('checked_out', dtype ='I', name_long ='!!Checked_Out', notnull ='y')  
        tbl.column('checked_out_time', dtype ='DH', name_long ='!!Checked_Out_Time', notnull ='y')  
        tbl.column('editor', dtype ='A', name_long ='!!Editor', size ='0:50')  
        tbl.column('custombannercode', dtype ='T', name_long ='!!Custombannercode')  
        tbl.column('catid', dtype ='I', name_long ='!!Catid', notnull ='y')  
        tbl.column('description', dtype ='T', name_long ='!!Description', notnull ='y')  
        tbl.column('sticky', dtype ='I', name_long ='!!Sticky', notnull ='y')  
        tbl.column('ordering', dtype ='I', name_long ='!!Ordering', notnull ='y')  
        tbl.column('publish_up', dtype ='DH', name_long ='!!Publish_Up', notnull ='y')  
        tbl.column('publish_down', dtype ='DH', name_long ='!!Publish_Down', notnull ='y')  
        tbl.column('tags', dtype ='T', name_long ='!!Tags', notnull ='y')  
        tbl.column('params', dtype ='T', name_long ='!!Params', notnull ='y')  
