# encoding: utf-8
from gnr.core.gnrbag import Bag,BagResolver
class Table(object):
    def config_db(self, pkg):
        tbl =  pkg.table('jos_contact_details',  pkey='id',name_long='jos_contact_details')
        tbl.column('id', dtype ='I', name_long ='!!Id', notnull ='y')  
        tbl.column('name', dtype ='A', notnull ='y', size ='0:255', name_long ='!!Name')  
        tbl.column('alias', dtype ='A', notnull ='y', size ='0:255', name_long ='!!Alias')  
        tbl.column('con_position', dtype ='A', name_long ='!!Con_Position', size ='0:255')  
        tbl.column('address', dtype ='T', name_long ='!!Address')  
        tbl.column('suburb', dtype ='A', name_long ='!!Suburb', size ='0:100')  
        tbl.column('state', dtype ='A', name_long ='!!State', size ='0:100')  
        tbl.column('country', dtype ='A', name_long ='!!Country', size ='0:100')  
        tbl.column('postcode', dtype ='A', name_long ='!!Postcode', size ='0:100')  
        tbl.column('telephone', dtype ='A', name_long ='!!Telephone', size ='0:255')  
        tbl.column('fax', dtype ='A', name_long ='!!Fax', size ='0:255')  
        tbl.column('misc', dtype ='T', name_long ='!!Misc')  
        tbl.column('image', dtype ='A', name_long ='!!Image', size ='0:255')  
        tbl.column('imagepos', dtype ='A', name_long ='!!Imagepos', size ='0:20')  
        tbl.column('email_to', dtype ='A', name_long ='!!Email_To', size ='0:255')  
        tbl.column('default_con', dtype ='I', name_long ='!!Default_Con', notnull ='y')  
        tbl.column('published', dtype ='I', name_long ='!!Published', notnull ='y')  
        tbl.column('checked_out', dtype ='I', name_long ='!!Checked_Out', notnull ='y')  
        tbl.column('checked_out_time', dtype ='DH', name_long ='!!Checked_Out_Time', notnull ='y')  
        tbl.column('ordering', dtype ='I', name_long ='!!Ordering', notnull ='y')  
        tbl.column('params', dtype ='T', name_long ='!!Params', notnull ='y')  
        tbl.column('user_id', dtype ='I', name_long ='!!User_Id', notnull ='y')  
        tbl.column('catid', dtype ='I', name_long ='!!Catid', notnull ='y')  
        tbl.column('access', dtype ='I', name_long ='!!Access', notnull ='y')  
        tbl.column('mobile', dtype ='A', notnull ='y', size ='0:255', name_long ='!!Mobile')  
        tbl.column('webpage', dtype ='A', notnull ='y', size ='0:255', name_long ='!!Webpage')  
