# encoding: utf-8
from gnr.core.gnrbag import Bag,BagResolver
class Table(object):
    def config_db(self, pkg):
        tbl =  pkg.table('jos_eventlist_settings',  pkey='None',name_long='jos_eventlist_settings')
        tbl.column('id', dtype ='I', name_long ='!!Id', notnull ='y')  
        tbl.column('oldevent', dtype ='I', name_long ='!!Oldevent', notnull ='y')  
        tbl.column('minus', dtype ='I', name_long ='!!Minus', notnull ='y')  
        tbl.column('showtime', dtype ='I', name_long ='!!Showtime', notnull ='y')  
        tbl.column('showtitle', dtype ='I', name_long ='!!Showtitle', notnull ='y')  
        tbl.column('showlocate', dtype ='I', name_long ='!!Showlocate', notnull ='y')  
        tbl.column('showcity', dtype ='I', name_long ='!!Showcity', notnull ='y')  
        tbl.column('showmapserv', dtype ='I', name_long ='!!Showmapserv', notnull ='y')  
        tbl.column('map24id', size ='0:20', dtype ='A', name_long ='!!Map24Id', notnull ='y')  
        tbl.column('gmapkey', size ='0:255', dtype ='A', name_long ='!!Gmapkey', notnull ='y')  
        tbl.column('tablewidth', size ='0:20', dtype ='A', name_long ='!!Tablewidth', notnull ='y')  
        tbl.column('datewidth', size ='0:20', dtype ='A', name_long ='!!Datewidth', notnull ='y')  
        tbl.column('titlewidth', size ='0:20', dtype ='A', name_long ='!!Titlewidth', notnull ='y')  
        tbl.column('locationwidth', size ='0:20', dtype ='A', name_long ='!!Locationwidth', notnull ='y')  
        tbl.column('citywidth', size ='0:20', dtype ='A', name_long ='!!Citywidth', notnull ='y')  
        tbl.column('datename', size ='0:100', dtype ='A', name_long ='!!Datename', notnull ='y')  
        tbl.column('titlename', size ='0:100', dtype ='A', name_long ='!!Titlename', notnull ='y')  
        tbl.column('locationname', size ='0:100', dtype ='A', name_long ='!!Locationname', notnull ='y')  
        tbl.column('cityname', size ='0:100', dtype ='A', name_long ='!!Cityname', notnull ='y')  
        tbl.column('formatdate', size ='0:100', dtype ='A', name_long ='!!Formatdate', notnull ='y')  
        tbl.column('formattime', size ='0:100', dtype ='A', name_long ='!!Formattime', notnull ='y')  
        tbl.column('timename', size ='0:50', dtype ='A', name_long ='!!Timename', notnull ='y')  
        tbl.column('showdetails', dtype ='I', name_long ='!!Showdetails', notnull ='y')  
        tbl.column('showtimedetails', dtype ='I', name_long ='!!Showtimedetails', notnull ='y')  
        tbl.column('showevdescription', dtype ='I', name_long ='!!Showevdescription', notnull ='y')  
        tbl.column('showdetailstitle', dtype ='I', name_long ='!!Showdetailstitle', notnull ='y')  
        tbl.column('showdetailsadress', dtype ='I', name_long ='!!Showdetailsadress', notnull ='y')  
        tbl.column('showlocdescription', dtype ='I', name_long ='!!Showlocdescription', notnull ='y')  
        tbl.column('showlinkvenue', dtype ='I', name_long ='!!Showlinkvenue', notnull ='y')  
        tbl.column('showdetlinkvenue', dtype ='I', name_long ='!!Showdetlinkvenue', notnull ='y')  
        tbl.column('delivereventsyes', dtype ='I', name_long ='!!Delivereventsyes', notnull ='y')  
        tbl.column('mailinform', dtype ='I', name_long ='!!Mailinform', notnull ='y')  
        tbl.column('mailinformrec', size ='0:150', dtype ='A', name_long ='!!Mailinformrec', notnull ='y')  
        tbl.column('mailinformuser', dtype ='I', name_long ='!!Mailinformuser', notnull ='y')  
        tbl.column('datdesclimit', size ='0:15', dtype ='A', name_long ='!!Datdesclimit', notnull ='y')  
        tbl.column('autopubl', dtype ='I', name_long ='!!Autopubl', notnull ='y')  
        tbl.column('deliverlocsyes', dtype ='I', name_long ='!!Deliverlocsyes', notnull ='y')  
        tbl.column('autopublocate', dtype ='I', name_long ='!!Autopublocate', notnull ='y')  
        tbl.column('showcat', dtype ='I', name_long ='!!Showcat', notnull ='y')  
        tbl.column('catfrowidth', size ='0:20', dtype ='A', name_long ='!!Catfrowidth', notnull ='y')  
        tbl.column('catfroname', size ='0:100', dtype ='A', name_long ='!!Catfroname', notnull ='y')  
        tbl.column('evdelrec', dtype ='I', name_long ='!!Evdelrec', notnull ='y')  
        tbl.column('evpubrec', dtype ='I', name_long ='!!Evpubrec', notnull ='y')  
        tbl.column('locdelrec', dtype ='I', name_long ='!!Locdelrec', notnull ='y')  
        tbl.column('locpubrec', dtype ='I', name_long ='!!Locpubrec', notnull ='y')  
        tbl.column('sizelimit', size ='0:20', dtype ='A', name_long ='!!Sizelimit', notnull ='y')  
        tbl.column('imagehight', size ='0:20', dtype ='A', name_long ='!!Imagehight', notnull ='y')  
        tbl.column('imagewidth', size ='0:20', dtype ='A', name_long ='!!Imagewidth', notnull ='y')  
        tbl.column('gddisabled', dtype ='I', name_long ='!!Gddisabled', notnull ='y')  
        tbl.column('imageenabled', dtype ='I', name_long ='!!Imageenabled', notnull ='y')  
        tbl.column('comunsolution', dtype ='I', name_long ='!!Comunsolution', notnull ='y')  
        tbl.column('comunoption', dtype ='I', name_long ='!!Comunoption', notnull ='y')  
        tbl.column('catlinklist', dtype ='I', name_long ='!!Catlinklist', notnull ='y')  
        tbl.column('showfroregistra', dtype ='I', name_long ='!!Showfroregistra', notnull ='y')  
        tbl.column('showfrounregistra', dtype ='I', name_long ='!!Showfrounregistra', notnull ='y')  
        tbl.column('eventedit', dtype ='I', name_long ='!!Eventedit', notnull ='y')  
        tbl.column('eventeditrec', dtype ='I', name_long ='!!Eventeditrec', notnull ='y')  
        tbl.column('eventowner', dtype ='I', name_long ='!!Eventowner', notnull ='y')  
        tbl.column('venueedit', dtype ='I', name_long ='!!Venueedit', notnull ='y')  
        tbl.column('venueeditrec', dtype ='I', name_long ='!!Venueeditrec', notnull ='y')  
        tbl.column('venueowner', dtype ='I', name_long ='!!Venueowner', notnull ='y')  
        tbl.column('lightbox', dtype ='I', name_long ='!!Lightbox', notnull ='y')  
        tbl.column('meta_keywords', size ='0:255', dtype ='A', name_long ='!!Meta_Keywords', notnull ='y')  
        tbl.column('meta_description', size ='0:255', dtype ='A', name_long ='!!Meta_Description', notnull ='y')  
        tbl.column('showstate', dtype ='I', name_long ='!!Showstate', notnull ='y')  
        tbl.column('statename', size ='0:100', dtype ='A', name_long ='!!Statename', notnull ='y')  
        tbl.column('statewidth', size ='0:20', dtype ='A', name_long ='!!Statewidth', notnull ='y')  
        tbl.column('regname', dtype ='I', name_long ='!!Regname', notnull ='y')  
        tbl.column('storeip', dtype ='I', name_long ='!!Storeip', notnull ='y')  
        tbl.column('commentsystem', dtype ='I', name_long ='!!Commentsystem', notnull ='y')  
        tbl.column('lastupdate', dtype ='A', notnull ='y', size ='0:20', name_long ='!!Lastupdate')  
        tbl.column('checked_out', dtype ='I', name_long ='!!Checked_Out', notnull ='y')  
        tbl.column('checked_out_time', dtype ='DH', name_long ='!!Checked_Out_Time', notnull ='y')  
