# encoding: utf-8
from gnr.core.gnrbag import Bag,BagResolver
class Table(object):
    def config_db(self, pkg):
        tbl =  pkg.table('jos_hwdpsphotos',  pkey='id',name_long='jos_hwdpsphotos')
        tbl.column('id', dtype ='I', name_long ='!!Id', notnull ='y')  
        tbl.column('photo_type', dtype ='A', name_long ='!!Photo_Type', size ='0:250')  
        tbl.column('photo_id', dtype ='A', name_long ='!!Photo_Id', size ='0:250')  
        tbl.column('thumb_id', dtype ='A', name_long ='!!Thumb_Id', size ='0:250')  
        tbl.column('album_id', dtype ='I', name_long ='!!Album_Id')  
        tbl.column('title', dtype ='T', name_long ='!!Title')  
        tbl.column('caption', dtype ='T', name_long ='!!Caption')  
        tbl.column('tags', dtype ='T', name_long ='!!Tags')  
        tbl.column('date_uploaded', dtype ='DH', name_long ='!!Date_Uploaded', notnull ='y')  
        tbl.column('location', dtype ='T', name_long ='!!Location')  
        tbl.column('allow_comments', dtype ='I', name_long ='!!Allow_Comments', notnull ='y')  
        tbl.column('allow_ratings', dtype ='I', name_long ='!!Allow_Ratings', notnull ='y')  
        tbl.column('rating_number_votes', dtype ='I', name_long ='!!Rating_Number_Votes')  
        tbl.column('rating_total_points', dtype ='I', name_long ='!!Rating_Total_Points')  
        tbl.column('updated_rating', dtype ='I', name_long ='!!Updated_Rating')  
        tbl.column('privacy', dtype ='A', name_long ='!!Privacy', size ='0:250')  
        tbl.column('approved', dtype ='A', name_long ='!!Approved', size ='0:250')  
        tbl.column('number_of_views', dtype ='I', name_long ='!!Number_Of_Views')  
        tbl.column('user_id', dtype ='I', name_long ='!!User_Id')  
        tbl.column('setcover', dtype ='I', name_long ='!!Setcover', notnull ='y')  
        tbl.column('original_type', dtype ='A', notnull ='y', size ='0:4', name_long ='!!Original_Type')  
        tbl.column('featured', dtype ='I', name_long ='!!Featured', notnull ='y')  
        tbl.column('ordering', dtype ='I', name_long ='!!Ordering', notnull ='y')  
        tbl.column('checked_out', dtype ='I', name_long ='!!Checked_Out', notnull ='y')  
        tbl.column('checked_out_time', dtype ='DH', name_long ='!!Checked_Out_Time', notnull ='y')  
        tbl.column('published', dtype ='I', name_long ='!!Published', notnull ='y')  
