# encoding: utf-8
from gnr.core.gnrbag import Bag,BagResolver
class Table(object):
    def config_db(self, pkg):
        tbl =  pkg.table('jos_eventlist_venues',  pkey='id',name_long='jos_eventlist_venues')
        tbl.column('id', dtype ='I', name_long ='!!Id', notnull ='y')  
        tbl.column('venue', dtype ='A', notnull ='y', size ='0:50', name_long ='!!Venue')  
        tbl.column('alias', dtype ='A', notnull ='y', size ='0:100', name_long ='!!Alias')  
        tbl.column('url', dtype ='A', notnull ='y', size ='0:200', name_long ='!!Url')  
        tbl.column('street', dtype ='A', name_long ='!!Street', size ='0:50')  
        tbl.column('plz', dtype ='A', name_long ='!!Plz', size ='0:20')  
        tbl.column('city', dtype ='A', name_long ='!!City', size ='0:50')  
        tbl.column('state', dtype ='A', name_long ='!!State', size ='0:50')  
        tbl.column('country', dtype ='A', name_long ='!!Country', size ='0:2')  
        tbl.column('locdescription', dtype ='T', name_long ='!!Locdescription', notnull ='y')  
        tbl.column('meta_keywords', dtype ='T', name_long ='!!Meta_Keywords', notnull ='y')  
        tbl.column('meta_description', dtype ='T', name_long ='!!Meta_Description', notnull ='y')  
        tbl.column('locimage', dtype ='A', notnull ='y', size ='0:100', name_long ='!!Locimage')  
        tbl.column('map', dtype ='I', name_long ='!!Map', notnull ='y')  
        tbl.column('created_by', dtype ='I', name_long ='!!Created_By', notnull ='y')  
        tbl.column('author_ip', dtype ='A', notnull ='y', size ='0:15', name_long ='!!Author_Ip')  
        tbl.column('created', dtype ='DH', name_long ='!!Created', notnull ='y')  
        tbl.column('modified', dtype ='DH', name_long ='!!Modified', notnull ='y')  
        tbl.column('modified_by', dtype ='I', name_long ='!!Modified_By', notnull ='y')  
        tbl.column('published', dtype ='I', name_long ='!!Published', notnull ='y')  
        tbl.column('checked_out', dtype ='I', name_long ='!!Checked_Out', notnull ='y')  
        tbl.column('checked_out_time', dtype ='DH', name_long ='!!Checked_Out_Time', notnull ='y')  
        tbl.column('ordering', dtype ='I', name_long ='!!Ordering', notnull ='y')  
