# encoding: utf-8
from gnr.core.gnrbag import Bag,BagResolver
class Table(object):
    def config_db(self, pkg):
        tbl =  pkg.table('jos_jomcomment',  pkey='id',name_long='jos_jomcomment')
        tbl.column('id', dtype ='I', name_long ='!!Id', notnull ='y')  
        tbl.column('parentid', dtype ='I', name_long ='!!Parentid', notnull ='y')  
        tbl.column('status', dtype ='I', name_long ='!!Status', notnull ='y')  
        tbl.column('contentid', dtype ='I', name_long ='!!Contentid', notnull ='y')  
        tbl.column('ip', dtype ='A', notnull ='y', size ='0:15', name_long ='!!Ip')  
        tbl.column('name', dtype ='A', name_long ='!!Name', size ='0:200')  
        tbl.column('title', dtype ='A', notnull ='y', size ='0:200', name_long ='!!Title')  
        tbl.column('comment', dtype ='T', name_long ='!!Comment', notnull ='y')  
        tbl.column('preview', dtype ='T', name_long ='!!Preview', notnull ='y')  
        tbl.column('date', dtype ='DH', name_long ='!!Date', notnull ='y')  
        tbl.column('published', dtype ='I', name_long ='!!Published', notnull ='y')  
        tbl.column('ordering', dtype ='I', name_long ='!!Ordering', notnull ='y')  
        tbl.column('email', dtype ='A', notnull ='y', size ='0:100', name_long ='!!Email')  
        tbl.column('website', dtype ='A', notnull ='y', size ='0:100', name_long ='!!Website')  
        tbl.column('updateme', dtype ='I', name_long ='!!Updateme', notnull ='y')  
        tbl.column('custom1', dtype ='A', notnull ='y', size ='0:200', name_long ='!!Custom1')  
        tbl.column('custom2', dtype ='A', notnull ='y', size ='0:200', name_long ='!!Custom2')  
        tbl.column('custom3', dtype ='A', notnull ='y', size ='0:200', name_long ='!!Custom3')  
        tbl.column('custom4', dtype ='A', notnull ='y', size ='0:200', name_long ='!!Custom4')  
        tbl.column('custom5', dtype ='A', notnull ='y', size ='0:200', name_long ='!!Custom5')  
        tbl.column('star', dtype ='I', name_long ='!!Star', notnull ='y')  
        tbl.column('user_id', dtype ='I', name_long ='!!User_Id', notnull ='y')  
        tbl.column('option', dtype ='A', notnull ='y', size ='0:50', name_long ='!!Option')  
        tbl.column('voted', dtype ='I', name_long ='!!Voted', notnull ='y')  
        tbl.column('referer', dtype ='A', notnull ='y', size ='0:255', name_long ='!!Referer')  
