# encoding: utf-8
from gnr.core.gnrbag import Bag,BagResolver
class Table(object):
    def config_db(self, pkg):
        tbl =  pkg.table('jos_hwdvidsvideos',  pkey='id',name_long='jos_hwdvidsvideos')
        tbl.column('id', dtype ='I', name_long ='!!Id', notnull ='y')  
        tbl.column('video_type', dtype ='A', name_long ='!!Video_Type', size ='0:250')  
        tbl.column('video_id', dtype ='T', name_long ='!!Video_Id', notnull ='y')  
        tbl.column('title', dtype ='T', name_long ='!!Title')  
        tbl.column('description', dtype ='T', name_long ='!!Description')  
        tbl.column('tags', dtype ='T', name_long ='!!Tags')  
        tbl.column('category_id', dtype ='I', name_long ='!!Category_Id')  
        tbl.column('date_uploaded', dtype ='DH', name_long ='!!Date_Uploaded', notnull ='y')  
        tbl.column('video_length', dtype ='A', name_long ='!!Video_Length', size ='0:250')  
        tbl.column('allow_comments', dtype ='I', name_long ='!!Allow_Comments', notnull ='y')  
        tbl.column('allow_embedding', dtype ='I', name_long ='!!Allow_Embedding', notnull ='y')  
        tbl.column('allow_ratings', dtype ='I', name_long ='!!Allow_Ratings', notnull ='y')  
        tbl.column('rating_number_votes', dtype ='I', name_long ='!!Rating_Number_Votes')  
        tbl.column('rating_total_points', dtype ='I', name_long ='!!Rating_Total_Points')  
        tbl.column('updated_rating', dtype ='I', name_long ='!!Updated_Rating')  
        tbl.column('public_private', dtype ='A', name_long ='!!Public_Private', size ='0:250')  
        tbl.column('approved', dtype ='A', name_long ='!!Approved', size ='0:250')  
        tbl.column('number_of_views', dtype ='I', name_long ='!!Number_Of_Views')  
        tbl.column('user_id', dtype ='I', name_long ='!!User_Id')  
        tbl.column('featured', dtype ='I', name_long ='!!Featured', notnull ='y')  
        tbl.column('ordering', dtype ='I', name_long ='!!Ordering', notnull ='y')  
        tbl.column('checked_out', dtype ='I', name_long ='!!Checked_Out', notnull ='y')  
        tbl.column('checked_out_time', dtype ='DH', name_long ='!!Checked_Out_Time', notnull ='y')  
        tbl.column('published', dtype ='I', name_long ='!!Published', notnull ='y')  
