# encoding: utf-8
from gnr.core.gnrbag import Bag,BagResolver
class Table(object):
    def config_db(self, pkg):
        tbl =  pkg.table('jos_eventlist_events',  pkey='id',name_long='jos_eventlist_events')
        tbl.column('id', dtype ='I', name_long ='!!Id', notnull ='y')  
        tbl.column('locid', dtype ='I', name_long ='!!Locid', notnull ='y')  
        tbl.column('catsid', dtype ='I', name_long ='!!Catsid', notnull ='y')  
        tbl.column('dates', dtype ='D', name_long ='!!Dates', notnull ='y')  
        tbl.column('enddates', dtype ='D', name_long ='!!Enddates')  
        tbl.column('times', dtype ='H', name_long ='!!Times')  
        tbl.column('endtimes', dtype ='H', name_long ='!!Endtimes')  
        tbl.column('title', dtype ='A', notnull ='y', size ='0:100', name_long ='!!Title')  
        tbl.column('alias', dtype ='A', notnull ='y', size ='0:100', name_long ='!!Alias')  
        tbl.column('created_by', dtype ='I', name_long ='!!Created_By', notnull ='y')  
        tbl.column('modified', dtype ='DH', name_long ='!!Modified', notnull ='y')  
        tbl.column('modified_by', dtype ='I', name_long ='!!Modified_By', notnull ='y')  
        tbl.column('author_ip', dtype ='A', notnull ='y', size ='0:15', name_long ='!!Author_Ip')  
        tbl.column('created', dtype ='DH', name_long ='!!Created', notnull ='y')  
        tbl.column('datdescription', dtype ='T', name_long ='!!Datdescription', notnull ='y')  
        tbl.column('meta_keywords', dtype ='A', notnull ='y', size ='0:200', name_long ='!!Meta_Keywords')  
        tbl.column('meta_description', dtype ='A', notnull ='y', size ='0:255', name_long ='!!Meta_Description')  
        tbl.column('recurrence_number', dtype ='I', name_long ='!!Recurrence_Number', notnull ='y')  
        tbl.column('recurrence_type', dtype ='I', name_long ='!!Recurrence_Type', notnull ='y')  
        tbl.column('recurrence_counter', dtype ='D', name_long ='!!Recurrence_Counter', notnull ='y')  
        tbl.column('datimage', dtype ='A', notnull ='y', size ='0:100', name_long ='!!Datimage')  
        tbl.column('checked_out', dtype ='I', name_long ='!!Checked_Out', notnull ='y')  
        tbl.column('checked_out_time', dtype ='DH', name_long ='!!Checked_Out_Time', notnull ='y')  
        tbl.column('registra', dtype ='I', name_long ='!!Registra', notnull ='y')  
        tbl.column('unregistra', dtype ='I', name_long ='!!Unregistra', notnull ='y')  
        tbl.column('published', dtype ='I', name_long ='!!Published', notnull ='y')  
