#!/usr/bin/env python
# encoding: utf-8

"""
create a new genroproject
usage: gnrmkproject projectname

"""
import sys, os

from gnr.web.gnrasync import GnrAsyncServer
from optparse import OptionParser
from gnr.core.gnrsys import expandpath
from gnr.app.gnrconfig import gnrConfigPath,getSiteHandler,getGnrConfig

if __name__ == '__main__':
    usage = """
    gnrasync <site_name> will run a websocket server for <site_name> using tornado.
    """
    parser = OptionParser(usage)
    parser.add_option('-p', '--port',
                  dest='port',
                  help="Check only, don't apply changes")    
    (options, args) = parser.parse_args()
    if  len(args)<1:
        parser.print_help()
    else:
        server=GnrAsyncServer(port=getattr(options,'port',None),instance=args[0])
        server.start()


        
