#!/usr/bin/env python
# encoding: utf-8

"""
create a new genroproject
usage: gnrmkproject projectname

"""
import sys, os

from gnr.web.gnrasync import GnrAsyncServer
from optparse import OptionParser
from gnr.core.gnrsys import expandpath
from gnr.app.gnrconfig import gnrConfigPath,getSiteHandler,getGnrConfig

if __name__ == '__main__':
    usage = """
    gnrasync <site_name> will run a websocket server for <site_name> using tornado.
    """
    parser = OptionParser(usage)
    parser.add_option('-p', '--port',
                  dest='port',
                  help="Listen port")     
    parser.add_option('-c', '--crt',
                  dest='ssl_crt',
                  help="SSL Certificate path")        
    parser.add_option('-k', '--key',
                  dest='ssl_key',
                  help="SSL key path")    
    (options, args) = parser.parse_args()
    if  len(args)<1:
        parser.print_help()
    else:
        server=GnrAsyncServer(port=getattr(options,'port',None),instance=args[0],
            ssl_crt=getattr(options,'ssl_crt',None),ssl_key=getattr(options,'ssl_key',None))
        server.start()


        
