#!/usr/bin/env python2.7
# encoding: utf-8
# 
from gnr.core.gnrsys import expandpath
from gnr.core.gnrbag import Bag
from datetime import datetime
from time import time,sleep, localtime, strftime
from multiprocessing import Process, Pipe
from gnr.web.gnrwsgisite_proxy.gnrsiteregister import GnrSiteRegisterServer

import os


import argparse
import Pyro4

PYRO_HOST = 'localhost'
PYRO_PORT = 40004
PYRO_HMAC_KEY = 'supersecretkey'

def createSiteRegister(sitename=None,daemon_uri=None,host=None,hmac_key=None,storage_path=None,debug=None):
    print 'creating'
    server = GnrSiteRegisterServer(sitename=sitename,daemon_uri=daemon_uri,storage_path=storage_path,debug=debug)
    print 'starting'
    server.start(host=host,hmac_key=hmac_key,port='*')

class GnrDaemonProxy(object):
    def __init__(self,host=None,port=None,hmac_key=None,compression=False):
        Pyro4.config.HMAC_KEY = str(hmac_key or PYRO_HMAC_KEY)
        Pyro4.config.SERIALIZER = 'pickle'
        Pyro4.config.COMPRESSION = True
        self.uri = 'PYRO:GnrDaemon@%s:%s' %(host,port)
    
    def proxy(self):
        return Pyro4.Proxy(self.uri)

class GnrDaemon(object):
    def __init__(self):
        self.running = False
        self.siteregisters= dict()
        self.siteregisters_process = dict()

    def start(self,host=None,port=None,hmac_key=None,
                      debug=False,compression=False,timeout=None,
                      multiplex=False,polltimeout=None):
        self.pyroConfig(host=host,port=port,hmac_key=hmac_key,debug=debug,
                        compression=compression,timeout=timeout,
                        multiplex=multiplex,polltimeout=polltimeout)
                        
        self.daemon = Pyro4.Daemon(host=self.host,port=int(self.port))
        self.main_uri = self.daemon.register(self,'GnrDaemon')
        print "uri=",self.main_uri
        self.running = True
        self.daemon.requestLoop(lambda : self.running)
        
    def pyroConfig(self,host=None,port=None,hmac_key=None,
                      debug=False,compression=False,timeout=None,
                      multiplex=False,polltimeout=None):
        Pyro4.config.SERIALIZERS_ACCEPTED.add('pickle')
        self.port=port or PYRO_PORT
        self.host = host or PYRO_HOST
        self.hmac_key = str(hmac_key or PYRO_HMAC_KEY)
        Pyro4.config.HMAC_KEY = self.hmac_key
        if compression:
            Pyro4.config.COMPRESSION = True
        if multiplex:
            Pyro4.config.SERVERTYPE = "multiplex"
        if timeout:
            Pyro4.config.TIMEOUT = timeout
        if polltimeout:
            Pyro4.config.POLLTIMEOUT = timeout
    
    def registerSiteName(self,sitename,site_uri):
        self.siteregisters[sitename]['uri'] = site_uri
        print 'registered ',sitename,site_uri
        
    def ping(self):
        return 'ping'
    
    def getSiteUri(self,sitename=None,create=False,storage_path=None):
        if sitename in self.siteregisters and self.siteregisters[sitename]['uri']:
            return self.siteregisters[sitename]['uri']
        elif create:
            self.addSiteRegister(sitename,storage_path=storage_path)
            return False
        
    def stop(self,saveStatus=True):
        self.siteregister_stop('*',saveStatus=saveStatus)
        self.running = False
    
    def addSiteRegister(self,sitename,storage_path=None):
        if not sitename in self.siteregisters:
            print 'adding sitename',sitename
            childprocess = Process(name='sr_%s' %sitename, target=createSiteRegister,kwargs=dict(sitename=sitename,daemon_uri=self.main_uri,host=self.host,hmac_key=self.hmac_key,storage_path=storage_path))
            self.siteregisters[sitename] = dict(sitename=sitename,uri=False,start_ts=datetime.now())
            self.siteregisters_process[sitename] = childprocess
            childprocess.daemon = True
            childprocess.start()
        else:
            print 'ALREADY EXISTING ',sitename

    def siteRegisters(self):
        return self.siteregisters.items()
        
    def siteregister_dump(self,sitename):
        uri = self.siteregisters[sitename]['uri']
        return Pyro4.Proxy(uri).dump()
        

    def siteregister_load(self,sitename):
        uri = self.siteregisters[sitename]['uri']
        return Pyro4.Proxy(uri).load()
        
    def siteregister_stop(self,sitename,saveStatus=False):
        if sitename=='*':
            for k in self.siteregisters:
                self.siteregister_stop(k,saveStatus=saveStatus)
            return
        uri = self.siteregisters[sitename]['uri']
        return Pyro4.Proxy(uri).stop(saveStatus=saveStatus)
        
        
def getOptions():
    usage = "\ngnrdaemon"
    parser = argparse.ArgumentParser(usage)
    parser.add_argument('command',nargs='?')
    parser.add_argument('-H', '--host',
                      help="The binded host")
                      
    parser.add_argument('-P', '--port',
                      help="The binded port" ,type=int)
                      
    parser.add_argument('-K', '--hmac_key',
                      help="The secret key")
                      
    parser.add_argument('-t', '--timeout',type=float,
                      help="Timeout")

    parser.add_argument('-m', '--multiplex',action='store_false',
                      help="Use multiplexed server")
                      
    parser.add_argument('--polltimeout',type=float,
                      help="Use multiplexed server poll timeout")

    parser.add_argument('-d', '--debug',
                      action='store_false',
                      help="Debug mode")
                      
    parser.add_argument('-c', '--compression',
                      action='store_false',
                      help="Enable compression")

    parser.add_argument('-s', '--savestatus',
                      action='store_true',
                      help="Save status")

    arguments= parser.parse_args()
    return arguments.__dict__
    
    

if __name__=="__main__":
    curropt = getOptions()
    options = Bag(expandpath('~/.gnr/environment.xml')).getAttr('gnrdaemon')
    assert options,"Missing gnrdaemon configuration."
    for k,v in curropt.items():
        if v:
            options[k] = v
    command = options.pop('command',None)
    if command == 'start' or not command:
        server = GnrDaemon()
        server.start(**options)
    else:
        p = GnrDaemonProxy(host=options.get('host'),port=options.get('port'),hmac_key=options.get('hmac_key'),compression=options.get('compression'))
        proxy = p.proxy()
        if command=='stop':
            print 'savestatus',options.get('savestatus')
            result = proxy.stop(saveStatus=options.get('savestatus'))   
            print result
        elif command in ('stopping','starting'):
            result = getattr(proxy,command)()
            print result
        else:
            print 'unknown command:%s' %command