#!/usr/bin/env python2.7
# encoding: utf-8
# 
from gnr.web.gnrdaemonhandler import GnrDaemon,GnrDaemonProxy


import argparse

PYRO_HOST = 'localhost'
PYRO_PORT = 40004
PYRO_HMAC_KEY = 'supersecretkey'
 
def getOptions():
    usage = "\ngnrdaemon"
    parser = argparse.ArgumentParser(usage)
    parser.add_argument('command',nargs='?')
    parser.add_argument('-H', '--host',
                      help="The binded host")
                      
    parser.add_argument('-P', '--port',
                      help="The binded port" ,type=int)
                      
    parser.add_argument('-S', '--socket',
                      help="socket to use")
                      
    parser.add_argument('-K', '--hmac_key',
                      help="The secret key")
                      
    parser.add_argument('-t', '--timeout',type=float,
                      help="Timeout")

    parser.add_argument('-m', '--multiplex',action='store_false',
                      help="Use multiplexed server")
                      
    parser.add_argument('--polltimeout',type=float,
                      help="Use multiplexed server poll timeout")

    parser.add_argument('-d', '--debug',
                      action='store_false',
                      help="Debug mode")
                      
    parser.add_argument('-c', '--compression',
                      action='store_false',
                      help="Enable compression")

    parser.add_argument('-s', '--savestatus',
                      action='store_true',
                      help="Save status")

    parser.add_argument('-n', '--sitename',
                      help="Sitename")
    
    parser.add_argument('-l', '--size_limit', type=int,
                      help="Size limit")

    parser.add_argument('-L', '--loglevel', type=int,
                       help="Log level")
    arguments= parser.parse_args()

    return arguments.__dict__

SERVICE_TPL = """
[Unit]
Description=GnrDaemon Service
After=multi-user.target

[Service]
Type=idle
%(environments)s
ExecStart=%(binpath)s

[Install]
WantedBy=multi-user.target
"""

if __name__=="__main__":
    options = getOptions()
    command = options.pop('command',None)
    if command == 'start' or not command:
        server = GnrDaemon()
        server.start(use_environment=True,**options)
    elif command=='make_service':
        import os
        import sys

        if os.environ.has_key('VIRTUAL_ENV'):
            environments = "Environment=VIRTUAL_ENV=%s" %os.environ['VIRTUAL_ENV']
        else:
            environments = ''
        
        binpath = sys.argv[0]
        content = SERVICE_TPL %dict(environments=environments,binpath=binpath)
        with open('gnrdaemon.service','w') as service_file:
            service_file.write(content)
        print """
Now using run these commands

$ sudo cp gnrdaemon.service /lib/systemd/system/bong.service
$ sudo chmod 644 /lib/systemd/system/gnrdaemon.service
$ sudo systemctl daemon-reload  # Refresh the available service list
$ sudo systemctl enable gnrdaemon.service

# Now watch your service auto run at bootup
$ sudo reboot
...
$ sudo systemctl status gnrdaemon.service
$ sudo journalctl -e -u gnrdaemon.service
        """
    else:
        p = GnrDaemonProxy(use_environment=True, host=options.get('host'),port=options.get('port'),socket=options.get('socket'),hmac_key=options.get('hmac_key'),compression=options.get('compression'))
        proxy = p.proxy()
        if command=='stop':
            print 'savestatus',options.get('savestatus')
            result = proxy.stop(saveStatus=options.get('savestatus'))   
            print result
        elif command =='restart':
            result = proxy.restart(sitename='*')
        elif command in ('stopping','starting'):
            result = getattr(proxy,command)()
            print result
        else:
            h = getattr(proxy,command,None)
            if h:
                print h(**options)
            else:
                print 'unknown command:%s' %command