#!/usr/bin/env python
# encoding: utf-8
from __future__ import print_function
from future import standard_library
standard_library.install_aliases()
import urllib.request, urllib.parse, urllib.error
import sys

argv = sys.argv
argv.pop(0)
path = ''
port = argv.pop(0)
if argv:
    path = sys.argv[0] or ''
    path = path.replace('.', '/')
urlobj = urllib.request.urlopen('http://127.0.0.1:%s/_tools/dbstructure/%s' % (port, path))
print(urlobj.read())