#!/usr/bin/env python
# encoding: utf-8

"""
create a new deploy gunicorn nginx websocket environment for a site
usage: gnrdeploybuilder site

"""
import os
import sys
import pwd
import shutil

from gnr.app.gnrdeploy import GunicornDeployBuilder, gnrdaemonServiceBuilder
from gnr.app.gnrdeploy import gnrsiterunnerServiceBuilder,createVirtualEnv
from optparse import OptionParser



if __name__ == '__main__':
    usage = """
    gnrdeploybuilder can create:
        - nginx virtualhosts
        - gnrsiterunner systemd services
        - gnrdaemon services
        - virtualenvs
    """
    parser = OptionParser()
    parser.add_option("-d", "--domain", dest="domain",
                      help="The nginx domain")
    parser.add_option('-s', '--make_service',dest='make_service',
                      action="store_true", help="Make service")
    parser.add_option('-e', '--make_virtualenv',dest='make_virtualenv',
                       help="Make virtualenv")
    parser.add_option('-g', '--make_gnrdaemon',dest='make_gnrdaemon',
                       action="store_true", help="Make gnrdaemon service")
    parser.add_option('-c', '--copy_genropy',dest='copy_genropy',
                      action="store_true", help="Copy genropy")
    parser.add_option('-p', '--copy_projects',dest='copy_projects',
                       help="Copy projects")
    parser.add_option('-b', '--branch',dest='branch',
                       help="Switch in genropy branch (if making a virtualenv and copy_genropy is set)")

    (options, args) = parser.parse_args()
    base_path = getattr(options,'base_path', None)
    if not (args or options.make_virtualenv or options.make_gnrdaemon or options.make_service):
        parser.print_help()
    if options.make_virtualenv:
        createVirtualEnv(name=options.make_virtualenv, copy_genropy=options.copy_genropy,
            branch=options.branch, copy_projects=options.copy_projects)
    if args:
        deployer = GunicornDeployBuilder(args[0])
        deployer.write_gunicorn_conf()
        deployer.local_supervisor_conf()
        deployer.main_supervisor_conf()
        if options.domain:
            print 'Writing nginx conf in cwd please copy in /etc/nginx/sites-enabled'
            deployer.write_nginx_conf(options.domain)
    if options.make_gnrdaemon:
        gnrdaemonServiceBuilder()
    if options.make_service:
        gnrsiterunnerServiceBuilder()