#!/usr/bin/env python
# encoding: utf-8

"""
create a new genroproject
usage: gnrmkproject projectname

"""
import sys, os

from gnr.app.gnrapp import GnrApp
import optparse

if __name__ == '__main__':
    usage = """
    gnrlocalizer <instance_name> will analize packages of related instance
    and update localization.xml file in every package.
    """
    parser = optparse.OptionParser(usage)
    parser.add_option('-a', '--all',
                dest='scan_all',
                action='store_true',
                help="Scan also genro source")
    parser.add_option('-t', '--translate',
                dest='translations',
                action='store_true',
                help="Translate")
                      
    (options, args) = parser.parse_args()
    if  len(args)<1:
        parser.print_help()
    else:
        app = GnrApp(args[0])
        translations = getattr(options,'translations',None)
        if translations:
            app.localizer.autoTranslate('en,it,fr,de')
        app.localizer.updateLocalizationFiles(scan_all=getattr(options,'scan_all',None))

        
