#!/usr/bin/env python
# encoding: utf-8

"""
create a new genroproject
usage: gnrmkproject projectname

"""
import sys, os, shutil

from gnr.core.gnrbag import Bag
from gnr.app.gnrapp import GnrApp
from gnr.app.gnrdeploy import PackageMaker, PathResolver
from optparse import OptionParser

if __name__ == '__main__':
    parser = OptionParser()
    parser.add_option("-b", "--base-path", dest="base_path",
                      help="base path where project will be created")

    (options, args) = parser.parse_args()
    base_path = getattr(options, 'base_path', None)
    if not args:
        print 'You should specify a package name'
    else:
        package_name = args[0]
        if '.' in args[0]:
            path_resolver = PathResolver()
            project_name, package_name = args[0].split('.')
            base_path = base_path or os.path.join(path_resolver.project_name_to_path(project_name), 'packages')
        print 'Creating package %s in %s...' % (package_name, base_path or 'current directory')
        package_maker = PackageMaker(package_name, base_path=base_path)
        print 'Package %s created' % package_name
        package_maker.do()
        