#!/usr/bin/env python
# encoding: utf-8

from gnr.lib.services.rms import RMS
from optparse import OptionParser


def main(instance,options):
    rms = RMS()
    rms.registerInstance(instance)


if __name__ == '__main__':
    usage = """

    """

    parser = OptionParser(usage)
    #parser.add_option('--avoid_connection',
    #              dest='avoid',
    #              action='store_true',
    #              help="Avoid connection")
    #parser.add_option('--no_nginx_parsing',
    #              dest='no',
    #              action='store_true',
    #              help="Avoid connection")

    (options, args) = parser.parse_args()
    instance = args[0] if args else None
    main(instance,options)