#!/usr/bin/env python
# encoding: utf-8



from gnr.core.gnrbag import Bag
from gnr.app.gnrapp import GnrApp
from gnr.app.gnrconfig import gnrConfigPath, getGnrConfig
from optparse import OptionParser

import os


class UwsgiUpdater(object):
    def __init__(self):
        self.gnr_config = getGnrConfig()
        self.gnr_path = gnrConfigPath()
        self.gnr_vassal_options = dict()
        self.socket_path = os.path.join(self.gnr_path, 'sockets')
        home_path = os.environ.get('HOME', '')
        if home_path.startswith('/containers'):
            default_vassals_path = os.path.join(home_path, 'vassals')
        else:
            default_vassals_path = os.path.join(self.gnr_path, 'uwsgi', 'vassals')
        self.vassals_path = self.gnr_config['gnr.environment_xml.vassals?path'] or default_vassals_path
        #self.vassals_path = os.path.join(self.gnr_path, 'uwsgi', 'vassals')
        self.create_dirs()

    def create_dirs(self):
        for dir_path in (self.socket_path, self.vassals_path):
            if not os.path.exists(dir_path):
                os.makedirs(dir_path)

    def get_config(self):
        site_config_path = os.path.join(self.site_path, 'siteconfig.xml')
        base_site_config = Bag(site_config_path)
        site_config = self.gnr_config['gnr.siteconfig.default_xml'] or Bag()
        template = self.site_template
        if template:
            site_config.update(self.gnr_config['gnr.siteconfig.%s_xml' % template] or Bag())
        site_config.update(base_site_config)
        return site_config

    def update(self):
        instances = [os.path.splitext(l)[0] for l in os.listdir(self.vassals_path) if l not in ('gnrdaemon.ini','pg.ini')]
        for s in instances:
            print 'Instance ',s
            self.stop_vassal(s)
            print '\t server stopped'
            app = GnrApp(s)
            print '\t running dbsetup'
            changes = self.check_db(app)
            if changes:
                print 'APPLYING CHANGES TO DATABASE...'
                app.db.model.applyModelChanges()
                print 'CHANGES APPLIED TO DATABASE'
            #app.db.model.checker.addExtesions()
            print '\t done'
        self.restart_vassal('gnrdaemon')
        for s in instances:
            print 'starting', s
            self.start_vassal(s)
        print 'Update ok'

    def touchonly(self):
        instances = [os.path.splitext(l)[0] for l in os.listdir(self.vassals_path) if l not in ('gnrdaemon.ini','pg.ini')]
        for s in instances:
            print 'Instance ',s
            self.restart_vassal(s)
            print 'restarted',s
        print 'touch ok'

    def stop_vassal(self,name):
        vassal_start_path = os.path.join(self.vassals_path,'%s.ini' %name)
        vassal_off_path = os.path.join(self.vassals_path, '%s.off' %name)
        if os.path.exists(vassal_start_path):
            os.rename(vassal_start_path, vassal_off_path)
            print "Site %s stopped" % name

    def start_vassal(self,name):
        vassal_start_path = os.path.join(self.vassals_path,'%s.ini' %name)
        vassal_off_path = os.path.join(self.vassals_path, '%s.off' %name)
        if os.path.exists(vassal_off_path):
            os.rename(vassal_off_path, vassal_start_path)
            print "Site %s start" % name

    def restart_vassal(self,name):
        self.stop_vassal(name)
        self.start_vassal(name)

        #vassal_path = os.path.join(self.vassals_path,'%s.ini' %name)
        #if os.path.exists(vassal_path):
        #    with open(vassal_path, 'a'):
        #        os.utime(vassal_path,None)
        #    print "Vassal %s restarted" % name

    def check_db(self,app):
        changes = app.db.model.check()
        dbname = app.db.currentEnv.get('storename')
        dbname = dbname or 'Main'
        print 'DB %s:' % dbname
        if changes:
            print 'STUCTURE NEEDS CHANGES'
        else:
            print 'STRUCTURE OK'
        return changes



if __name__ == '__main__':
    usage = """
    gnrupdate
    -to, --touchonly avoid dbsetup
    """

    parser = OptionParser(usage)
    parser.add_option('--touchonly',
                  dest='touchonly',
                  action='store_true',
                  help="Touch all vassals")  


    (options, args) = parser.parse_args()

    updater = UwsgiUpdater()
    if options.touchonly:
        updater.touchonly()
    else:
        updater.update()
    