#!/usr/bin/env python
# encoding: utf-8

import subprocess
import os

def main():
    hostname = os.environ.get('HOSTNAME' )
    if os.environ.get('GNR_WSGI_MODE' ) == 'uwsgi':
        hostpath = '/shared_data/%s' %hostname
        if not os.path.exists(hostpath):
            os.makedirs(hostpath)
        os.chmod(hostpath,0777)
        subprocess.call(['uwsgi','--socket', '%s/uwsgi.sock' %hostpath,
                        '--chdir' ,'/home/genropy_projects/sandbox/sites/sandbox',
                        '--wsgi-file', '/home/genropy_projects/sandbox/sites/sandbox/root.py',
                         '--master', '--processes', '4' ,'--threads' ,'2','--chmod-socket=777'
                        ])
    else:
        subprocess.call(['gnrwsgiserve'])


if __name__ == '__main__':
    main()